config/routes.rb
Galeria::Application.routes.draw do
  resources :ratings

  resources :models

  root :to => 'photos#index'
  match '/' => 'photos#index'
  match '/users/find' => 'users#find'
  
  resources :photos
  resources :images

  get "sessions/new"
resources :sessions, :only => [:new, :create, :destroy]
  resources :comments

  resources :users

 match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/rating.rb
class Rating < ActiveRecord::Base
attr_accessible :value

    belongs_to :photo
    belongs_to :user
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
    def create
            @photo = Photo.find_by_id(params[:photo_id])
            if current_user.id == @photo.id
                redirect_to photo_path(@photo), :alert => "Nie mozesz oceniac wlasnego zdjecia"
            else
                @rating = Rating.new(params[:rating])
                @rating.photo_id = @photo.id
                @rating.user_id = current_user.id
                if @rating.save
                    respond_to do |format|
                        format.html { redirect_to photo_path(@photo), :notice => "Ocena zostala dodana" }
                        format.js
                    end
                end
            end
        end

        def update
            @photo = Photo.find_by_id(params[:photo_id])
            if current_user.id == @photo.id
                redirect_to photo_path(@photo), :alert => "Nie mozesz oceniac wlasnego zdjecia"
            else
                @rating = current_user.ratings.find_by_photo_id(@photo.id)
                if @rating.update_attributes(params[:rating])
                    respond_to do |format|
                        format.html { redirect_to photo_path(@photo), :notice => "Ocena zostala zmieniona" }
                        format.js
                    end
                end
            end
        end

end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= simple_form_for(@rating) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :user_id %>
    <%= f.input :photo_id %>
    <%= f.input :value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/ratings/create.js.erb
$('table#rating').replaceWith("<%= escape_javascript(render :partial => 'photos/rating') %>");

app/views/ratings/edit.html.erb
<h1>Editing rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h1>Listing ratings</h1>

<table>
  <tr>
    <th>User</th>
    <th>Photo</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ratings.each do |rating| %>
  <tr>
    <td><%= rating.user_id %></td>
    <td><%= rating.photo_id %></td>
    <td><%= rating.value %></td>
    <td><%= link_to 'Show', rating %></td>
    <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
    <td><%= link_to 'Destroy', rating, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New rating</h1>

<%= render 'form' %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @rating.user_id %>
</p>

<p>
  <b>Photo:</b>
  <%= @rating.photo_id %>
</p>

<p>
  <b>Value:</b>
  <%= @rating.value %>
</p>


<%= link_to 'Edit', edit_rating_path(@rating) %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/update.js.erb
$('table#rating').replaceWith("<%= escape_javascript(render :partial => 'photos/rating') %>");