config/routes.rb
Galeria::Application.routes.draw do
  resources :ratings

  resources :models

  root :to => 'photos#index'
  match '/' => 'photos#index'
  match '/users/find' => 'users#find'
  
  resources :photos
  resources :images

  get "sessions/new"
resources :sessions, :only => [:new, :create, :destroy]
  resources :comments

  resources :users

 match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  # Keep in mind you can assign values other than :controller and :action

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  # root :to => 'welcome#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/photo.rb
class Photo < ActiveRecord::Base
has_many :ratings
has_many :raters, :through => :ratings, :source => :users

attr_accessible :name, :user_id, :image
belongs_to :user
has_many :comments
mount_uploader :image, ImageUploader

def average_rating
    @value = 0
    self.ratings.each do |rating|
        @value = @value + rating.value
    end
    @total = self.ratings.size
    @value.to_f / @total.to_f
end



end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController


  def index
    @photos = Photo.page(params[:page]).per(4)
   
@users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
	@comments = @photo.comments.page(params[:page]).per(5)
	@user= User.find(@photo.user_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to :back}
      else
        format.html { render :action => "new" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        redirect_to session['return-to']
      else
        format.html { render :action => "edit" }
        format.json { render :json => @photo.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

 
  
end

app/helpers/photos_helper.rb
module PhotosHelper
def rating_ballot
    if 	current_user.ratings.blank?
       current_user.ratings.new 
    else
       current_user.ratings.new 
    end
end
def current_user_rating
    if @rating = current_user.ratings.find_by_photo_id(params[:id])
        @rating.value
    else
        ""
    end
end
end

app/views/photos/_comment.html.erb
<%= stylesheet_link_tag 'Style1' %>
<div class="input">

<% unless current_user.blank? %>
<h2> Dodaj komentarz </h2>
<%= simple_form_for @photo.comments.build do |f| %>

  <%= f.text_area :content, :input_html => {:rows => 4, :cols => 40}, :class => "create_comment" %>
 <%=f.hidden_field :photo_id, :value => @photo.id %>
 <%=f.hidden_field :user_id, :value => current_user.id %>
  <br><%= f.button :submit, :value => "Wyslij" %>
 
  <% end %>
<% end %><p id="srednia">
<% if current_user.blank? %>
 Aby dodać komentarz <%= link_to " zarejestruj sie" , signup_path %> lub <%= link_to "zaloguj" , signin_path %> 

<%end%></p>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="insert"> 
    <p>Nazwa zdjęcia
    <%= f.text_field :name %>
    <%=f.hidden_field :user_id, :value => current_user.id %></p>
    <p>Plik:      <%= f.file_field :image %></p>
 

    <p><%= f.submit 'Prześlij' %></p>

  </div>
  </br>
<% end %>

app/views/photos/_photo.html.erb
<h2> Add photo </h2>
<%= simple_form_for @photo.build do |f| %>

  <%= f.text_area :name, :input_html => {:rows => 4, :cols => 40}, :class => "create_comment" %>
  <%= f.file_field :image %>
 <%=f.hidden_field :user_id, :value => @user.id %>
 <%=f.hidden_field :user_id, :value => current_user.id %> </div>
  <br><%= f.button :submit, :value => "Submit" %>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<html> 	
<div id="menu">

<% if !current_user.blank?%>
Witaj <span><%= current_user.name %></span><b></b><%= link_to 'Dodaj nowe zdjęcie', new_photo_path, :class => "loguj" %><%= link_to "Wyloguj się", signout_path, :class => "loguj" %>
<%end%>

<% if current_user.blank? %>
Chcesz dodać zdjęcie?
<%= link_to "zarejestruj się" , signup_path, :class => "loguj" %> 
<%= link_to "zaloguj" , signin_path, :class => "loguj"  %>
 <%end%>

<div class="menu"><ul><li>zdjęcia użytkowników:<ul>
<li><% @users.each do |user| %>
    
      <%= link_to user.name, user %>
    
  <% end %></li>
  </ul>
  </li>
  </ul></div>

</div>

<body> 

<div id="naglowek">

<h1>Photoblog <span>- chwile w obiektywie </span></h1>
</div>



</div>  


 

<div id="ramka"> 
<center>
<ul>
<%= paginate @photos %> 
<br>

<% @photos.each do |photo| %>

    <li>
   <%= link_to image_tag(photo.image), photo %>
 </li>
<% end %>
</ul>
</div></center>
<p id="uzytkownicy">
<p>

  </p>
 </p>
</body> 
<% session['return-to'] = request.fullpath %>

</html> 

app/views/photos/new.html.erb
<div id="menu">
<%= link_to "Strona główna", root_url,  :class => "loguj" %> </div>
<div id="naglowek">
<h1>Nowe zdjęcia</h1>
</div> 

<%= render 'form' %>

app/views/photos/show.html.erb
<div id="menu">
<%= link_to "Strona glowna", root_url,  :class => "loguj" %> 
<% if !current_user.blank?%>
<div class="menu">Witaj <span class="1"><%= current_user.name %></span> <%= link_to "Wyloguj sie", signout_path, :class => "loguj" %>
<%end%>	</div>
</div>
<div class="wrapper">
<%= stylesheet_link_tag 'Style1' %>
<p id="notice"><%= notice %></p>
<p id="notice"><%= alert %></p>


<div id="naglowek"> 
<h1><% if !@photo.name.blank? %> <%= @photo.name %><% else %> Untitled <% end %></h1>
</div>
<p><%= image_tag @photo.image %></p>
<% if !current_user.blank? %>    
<% if current_user.id == @photo.user_id %><%= link_to "Usun zdjecie", {:controller => :photos,
      :action => 'destroy', :id => @photo.id, :class => "TutajWstawiamyNazweKlasy" }, :method => :delete %><%end%><%end%>
<p id="dodane"> Dodane przez:<%= @user.name %></p>
<% if !@photo.average_rating.blank? %> <p id="srednia">Srednia ocena: <%= @photo.average_rating %> <% end %>
<p id="srednia">

<center>
<% if !current_user.blank? %>  
<% if current_user_rating.blank? %>
Oceń
<%= form_for(rating_ballot, :html => { :class => 'rating_ballot' }) do |f| %>
    <%= f.label("value_1", content_tag(:span, '1'), {:class=>"rating", :id=>"1"}) %>
    <%= radio_button_tag("rating[value]", 1, current_user_rating == 1, :class => 'rating_button') %>
    <%= f.label("value_2", content_tag(:span, '2'), {:class=>"rating", :id=>"2"}) %>
    <%= radio_button_tag("rating[value]", 2, current_user_rating == 2, :class => 'rating_button') %>
    <%= f.label("value_3", content_tag(:span, '3'), {:class=>"rating", :id=>"3"}) %>
    <%= radio_button_tag("rating[value]", 3, current_user_rating == 3, :class => 'rating_button') %>
    <%= f.label("value_4", content_tag(:span, '4'), {:class=>"rating", :id=>"4"}) %>
    <%= radio_button_tag("rating[value]", 4, current_user_rating == 4, :class => 'rating_button') %>
    <%= f.label("value_5", content_tag(:span, '5'), {:class=>"rating", :id=>"5"}) %>
    <%= radio_button_tag("rating[value]", 5, current_user_rating == 5, :class => 'rating_button') %>

    <%= hidden_field_tag("photo_id", @photo.id) %>

<% end %>
<% end %>
<% end %>
<% if !current_user.blank? %>  
<% if !current_user_rating.blank? %>  
 <p id="srednia">Twoja ocena <%= current_user_rating %> </p><%end%><%end%>
 <p id="srednia"><% if current_user.blank? %> Aby dodać ocene <%= link_to "zaloguj sie" , signin_path, :class => "loguj" %> <% end %></p>
</center>
</p>

<%= paginate @comments %> 
    <% @comments.each do |comm| %>
   
    <table id="comment">
    <tr> <hr></tr>
     <tr><td>Dodane przez: <span class="user"><%= comm.user.name %> </span><%= comm.created_at %> </td></tr>
     <tr id="comment"><td id="comment"><%= comm.content %> </td></tr>
     </table>
<% end %>

<%= render 'comment' %>
    <% session['return-to'] = request.fullpath %>